[TEAM-06, 제인, 이노] 기본 기능 및 OAuth 로그인 구현 후 PR 중입니다.
codesquad-members-2021/issue-tracker pull request #7
Opened 2021-06-11 15:22 UTC by janeljs

안녕하세요, 제인 & 이노입니다🙂
기본 기능 및 OAuth 로그인 구현 후 PR을 드립니다.

## 구현한 기능
### 이슈
-  이슈 닫기, 열기
-  이슈 생성 페이지 요청
-  이슈 생성
-  이슈 상세 페이지 조회
-  이슈 제목 편집
-  이슈 담당자 & 레이블 & 마일스톤 조회, 편집
-  이슈 코멘트 생성, 편집, 삭제

### 레이블
-  레이블 전체 조회
-  레이블 추가
-  레이블 편집
-  레이블 삭제

### 마일스톤
-  마일스톤 전체 조회
-  마일스톤 생성
-  마일스톤 수정
-  마일스톤 삭제

### OAuth
- 로그인
- 로그아웃

소중한 시간을 내어 리뷰해주셔서 감사합니다!

2021-06-11 15:35 UTC, realsigridjin commented
feat. PR 올린 거 게더타운에서 관전한 시그리드 @jypthemiracle 노을 @sanhee

2021-06-13 16:09 UTC, ksundong requested changes
안녕하세요~ 제인, 이노! 리뷰어 Dion입니다! 리뷰가 늦어져서 죄송합니다~
아직 1주차일텐데 굉장히 많은 코드가 작성되었네요. 고생 많으셨습니다.

- WebFlux를 시도해보신 점은 좋았습니다. 다만, 결국 Spring 프로젝트기 때문에, Spring을 사용하면서 지금까지 배워왔던 내용을 꼭 적용시켜가면서 사용해주세요.
- QueryDSL 의존성은 있는데 아직 사용은 하지 않으신 것 같네요. QueryDSL을 사용해서 보다 DB를 적극적으로 이용해보시기 바랍니다.
- 전반적으로 느껴지는 느낌은 너무 DB를 다루지 않는 느낌이 많이 들었습니다. 몇몇 부분은 객체에서 처리해주는 것이 아니라 DB에서 처리해주는 것이 더 나은 부분이 있었습니다.
- 그리고 Lombok을 너무 남용하고 있습니다. 두 분이 보시기엔 깔끔한 코드가 되었겠지만, 저는 Lombok 뒤에 숨어있는 코드들이 보이기 때문에 깔끔하지 않다고 말씀드리고 싶습니다. 더 나은 코드의 방해물이 되는 느낌이었습니다.
- JPA는 어려운 기술입니다. 흔히 Java, 객체지향, DB에 대한 이해를 다지고 사용해야한다고 많이 얘기합니다. 그 다음 JPA에 대해서 또 학습해야합니다. JPA 기저에 깔려있는 기술을 모르면 고생을 할 수 밖에 없죠. 연관관계 설정부터 시작해서 굉장히 많은 부분이 추상화 되어있지만 그것을 모르면 개발이 되지 않는 아쉬운 기술이기도 합니다.
- 적절한 책임 분리는 읽기 좋은 코드를 만들어내는데 도움이 됩니다. 이에 대해서는 좀 더 도전을 해보시길 추천드릴게요.

앞으로의 프로젝트도 화이팅입니다. 리뷰에 대한 피드백을 남겨주세요.(어떻게 수정하겠다, 이해가 가지 않는다. 등)
피드백이 완료되면 머지하겠습니다. 고생많으셨습니다!

2021-06-13 16:09 UTC, ksundong commented on BE/build.gradle
> +	id 'org.springframework.boot' version '2.5.0'
2.5.0 이군요
되도록이면 0으로 끝나는 버전은 추천하지 않습니다.
아마 2.5.1이 나왔을거에요. 버전 업그레이드를 추천드립니다.

2021-06-13 16:09 UTC, ksundong commented on BE/build.gradle
> +	id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
구버전을 사용하는게 아니라면 굳이 필요 없을 것 같네요.
http://honeymon.io/tech/2020/07/09/gradle-annotation-processor-with-querydsl.html

2021-06-13 16:09 UTC, ksundong commented on BE/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-webflux'
webflux 의존성이 있네요??

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +import com.jane_eno.issue_tracker.auth.dto.AccessTokenRequestDTO;
보통 패키지명에는 언더스코어(\_)를 사용하지 않습니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final GitHubUtil gitHubUtil;
보통 Util 클래스를 의존성으로 등록하지는 않습니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final GitHubUtil gitHubUtil;
이런류의 클래스를 저는 Service종류로 네이밍 하는 편이고, 역할이 있다면 Service 대신 붙여주는 것이 좋습니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private String userUri;
제가 RequiredArgsConstructor를 안좋아하는 것에는 이유가 있는데요.
이것도 그 이유중 하나입니다.
생성자 주입으로 충분히 해결이 가능한 문제인데, 생성자가 감춰져서 생성자 주입이 가능하다는 사실을 망각하게 만듭니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
제가 아직 WebFlux를 사용해보진 않았지만, 기본적으로 생성해주는 무언가가 있지 않을까? 하는 생각이 드네요.
그리고, 의존성을 내부에서 생성하는 것은 별로 바람직하지 않습니다.
차라리 별도의 빈으로 등록하는 것은 어땠을까요?
그리고, Netty라는 구체적인 무언가를 소스코드에 드러내는 것도 그다지 추천하고 싶지 않습니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +                .clientSecret(gitHubUtil.verifyClientSecret(userAgent))
verify라는 단어의 의미상 뭔가 검증된 결과가 반환되거나, void여야 할 것 같습니다.
한 번 더 생각해보시는 걸 추천드립니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +                .blockOptional()
결과가 리턴될 때 까지 block 하는 것 같네요.
정확하진 않겠지만, 다른 기술을 사용하는 것과 큰 차이가 없을 수 있겠다는 생각이 들어요.
이 부분은 제가 더 공부를 해야할 부분이라서, 더 좋은 피드백을 드리지 못해 아쉽네요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/JwtAuthInterceptor.java
> +        String header = request.getHeader("Authorization");
`Authorization`을 별도의 상수로 관리하는게 어땠을까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/JwtAuthInterceptor.java
> +            throw new HttpProtocolViolationException();
`Bearer`도 상수로 뽑아주는 것이 좋을 것 같고요.
예외명은 잘 이해가 가지 않네요.
이것이 Protocol의 문제는 아닌 것 같거든요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/JwtAuthInterceptor.java
> +        Long userId = decodedJWT.getClaim(USER_ID).asLong();
이것도 JwtUtil이 해줄 수 있을 것 같은데요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/OAuth.java
> +    GitHubUserResponseDTO getUserInfo(String token);
인터페이스인데, 구체적인 정보가 드러나는 메서드가 있네요. 조심하는게 좋겠죠?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/GitHubUtil.java
> +public class GitHubUtil {
왜 Util이라고 네이밍 해주셨나요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/JwtUtil.java
> +@NoArgsConstructor
NoArgsConstructor를 지정해주신 이유가 있나요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/JwtUtil.java
> +                .acceptExpiresAt(60 * 100)
상수로 뽑아줘도 좋을 것 같네요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +    IOS("IssueTrackerIOS");
뭔가 신기한 방법이네요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +    IOS("IssueTrackerIOS");
아래 정적 메서드들을 보면 POSTMAN은 어떻게 될지 모르겠네요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +        String product = getUserAgent(userAgent);
userAgent에서 userAgent를 가져오는건가요?
차라리 객체를 받아오는 것은 어떨까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +    }
이 메서드를 객체 내부로 넣어버리면 되지 않을까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
음...

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    @NonNull
어디서 온 애노테이션인지 모르겠네요. Lombok일까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +                .createdDateTime(LocalDateTime.now())
기왕 JPA 쓰시는거 JPA Auditing도 한 번 도전해보세요!

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    }
👍

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    }
equals hashCode를 오버라이딩 하는건 어떨까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    private List<Label> labels;
ManyToMany는 지양해주세요~
1:N, N:1 매핑으로 풀어낼 수 있습니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    @ManyToOne
ManyToOne은 Default FetchType이 eager인데요. 보통 일반적으로는 어떤 연관관계 매핑이든 명시적으로 lazy를 사용한다고 합니다.
사실 이 부분은 직접 겪어보는게 좋지만, 필요한 시점에 정보를 불러오도록 하는 것이 좋다. 정도로 일단 답변하겠습니다.

직접 학습해보시는 것을 추천드려요~

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
이렇게 사용해주신 이유를 정리해보시면 좋을 것 같아요~

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
뭔가 이상한 메서드네요~
create라는 이름을 사용해야 하는 이유가 있었나요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +        this.title = title;
title만 바뀔 수 있는건가요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +        this.title = title;
저라면, 다른 Issue 객체를 받아서 업데이트 하던가
DTO를 이용해볼 것 같아요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
연관관계 편의 메서드라고 있는데 한 번 찾아서 반영해보세요.
comment에도 parent를 할당해줘야 하거든요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +        }
잘 이해가 안가는 로직이네요~

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +        }
0번째 코멘트는 못지우나요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
음 이게 도메인에 있어야 하는 이유는 무엇일까요?
궁금해지네요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
자칫잘못하면 LazyLoding으로 인해 N + 1 쿼리 문제가 발생할 것 같아보이는 코드네요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/IssueRepository.java
> +    @Transactional
트랜잭셔널은 이곳말고 더 좋은 위치가 있을겁니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/milestone/Milestone.java
> +        return issues.stream().filter(i -> !i.isOpen()).count();
isClosed를 만들어주는건 어떨까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/milestone/Milestone.java
> +        return issues.stream().filter(i -> !i.isOpen()).count();
물론 여기도 똑같이 LazyLoading 이슈가 발생할 수 있습니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/exception/ElementNotFoundException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
이 상태코드 맞을까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<Issue> closedIssues = issueRepository.findAllByIsOpenFalse();
만약을 한 번 가정해봅시다. 만약 이슈가 수천개 수만개 있다면 과연 어떻게 될까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<IssueResponseDTO> issues = filterByStatus(status).stream()
filterByStatus 메서드는 사용되는 곳과 너무 멀리 떨어져 있어서 오히려 가독성이 떨어집니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<IssueResponseDTO> issues = filterByStatus(status).stream()
그리고 이 서비스에 메서드가 너무 많다는 점도 주의깊게 볼만한 점입니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +                .closedIssue(closedIssues.size())
둘의 size만 가져다 쓸 것이라면, count 쿼리를 이용하는 것이 더 효율적입니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        }
과연 N번 쿼리해야할까요?
in 쿼리를 이용해봅시다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        System.out.println(issue.toString());
logger를 이용해줍시다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +    }
조회와 조작하는 서비스를 분리해보는걸 시도해보는건 어떨까 하는 생각이 드네요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +    }
책임이 분명하게 나눠질 수 있는 부분인데 왜 나눠주지 않으셨나요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +    }
status를 String으로 관리해주는건 별로 현명하지 않아보이네요.
boolean아니면 Enum으로 개선해보세요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/MilestoneService.java
> +    private final LabelRepository labelRepository;
왜 다른 Repository에 대한 의존성이 있을까요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
> +        this.token = null;
토큰이 DB에서 관리되는건 그리 바람직 하지 않은 것 같아요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
> +        this.token = null;
여기서 제가말한 토큰은 우리 서버의 토큰입니다.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/UserService.java
> +                () -> new ElementNotFoundException("Cannot find user by given user id.")
특정 Exception을 정의해주는게 좋아보여요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
> +    public void changeStatus(@RequestBody IssueNumbersRequestDTO issueNumbersRequestDTO, @RequestParam String status) {
둘이 혼용해서 써본적은 없는데, 혹시 이렇게 한 이유가 있나요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
> +    @LoginRequired
여기만 권한체크가 들어가는 이유가 있나요?

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
> +    @LoginRequired
권한체크가 누락된 부분이 있는 것 같아요.

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
> +        logger.debug("이슈의 단당자 편집 요청 확인: {}", updateAssigneesRequestDTO.toString());
오타가 있네요!

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/IssueRequestDTO.java
> +                .comments(new ArrayList<>(Collections.singletonList(new Comment(comment, LocalDateTime.now(), author))))
왜 이렇게 만들어주시는지는 잘 모르겠네요..

2021-06-13 16:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/web/dto/response/MilestoneDTO.java
> +    private final Long closedIssues;
count 아닌가요?? 뭔가 Long 형이면 안될 것 같은 이름이에요.

2021-06-14 05:29 UTC, janeljs commented on BE/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-webflux'
Web client를 사용하기 위해 추가하였습니다!

2021-06-14 05:39 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final GitHubUtil gitHubUtil;
Service로 변경하였습니다! JwtUtil도 동일한 방식으로 주입받고있는데 JwtService와 같은 형식으로 변경하는게 좋을까요?

2021-06-14 05:44 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private String userUri;
생성자 주입으로 충분히 해결 가능하다는 말이 어떤걸 두고 하시는 말씀인지 잘 모르겠습니다.
좀 더 자세히 설명해 주실 수 있을까요??
혹시 현재처럼 필드주입을 받는 것에 있어서 예상되는 문제가 있을까요??

2021-06-14 06:05 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
현재는 web client를 저곳에서만 사용하고 있어서 빈으로 등록하지 않았었는데 빈으로 등록하는 방향으로 수정해보겠습니다! 그런데 webclient를 해당 클래스에만 사용하는 경우에도 config에 빈으로 등록하는 게 나을지 궁금합니다!

2021-06-14 06:05 UTC, eNoLJ commented on BE/build.gradle
> +	id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
남겨주신 글보고 플러그인을 빼도록 시도를 해봤는데 여러 설정이 필요해서 이것저것 해보다 오류가 많이 나서 일단 적용은하지 못했습니다.
근데 저 한줄만 추가해서 사용을 할 수 있는데 여러가지 설정을 통해 제외를 해줄 필요성이 있을까요??
절대 적용하기 싫어서 그런건 아니고 궁금해서 여쭤봐요ㅋㅋㅋㅋ

2021-06-14 06:30 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +                .blockOptional()
현재는 동기 방식으로 처리하고있어 말씀주신대로 RestTemplate과 차이가 없습니다. 다만 RestTemplate이 곧 deprecated될 예정이라고 들어 web client를 사용해보았습니다.

2021-06-14 06:30 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +                .clientSecret(gitHubUtil.verifyClientSecret(userAgent))
`verifyClientId` -> `getClientId`로 변경했습니다.
혹시 염두에 두고 있던 이름이 있다면 알려주세요!!

2021-06-14 06:39 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/JwtAuthInterceptor.java
> +            throw new HttpProtocolViolationException();
`HttpProtocolViolationException` -> `HttpHeaderFormatException`으로 변경했습니다.

2021-06-14 06:42 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/JwtAuthInterceptor.java
> +        Long userId = decodedJWT.getClaim(USER_ID).asLong();
`JwtUtil`에 `getUserId()` 메소드를 만들어 적용했습니다.

2021-06-14 07:11 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/OAuth.java
> +    GitHubUserResponseDTO getUserInfo(String token);
구체적인 정보가 드러나는 메소드가 `getUserInfo()` 일까요?? 
근데 구체적인 정보가 무엇을 두고 말하는지 잘 이해를 못하겠어요. 좀 더 설명해주시면 감사하겠습니다!!

2021-06-14 07:12 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/GitHubUtil.java
> +public class GitHubUtil {
user agent 정보에 따라 client id와 secret을 반환해주는 역할만 하고있어 util성 클래스라고 생각했습니다. 현재는 GitHubService로 네이밍을 변경하였는데 어떤 기준으로 service와 util을 구분하면 좋을까요?

2021-06-14 07:14 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/JwtUtil.java
> +@NoArgsConstructor
허허... 지웠습니다!!

2021-06-14 07:19 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +    IOS("IssueTrackerIOS");
원래 호스트 헤더로 검증하려고 하다가 클라이언트 개발자들과 상의하여 user agent 값을 헤더에 넣는 방법으로 변경하였습니다! postman은 isFront와 isIOS 모두에서 true가 return되도록 처리해주었는데 postman도 분리하여 처리하거나 메서드 네이밍에 반영하는 것이 좋을까요?

2021-06-14 07:37 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +        String product = getUserAgent(userAgent);
`auth.dto` 패키지에 `UserAgent`라는 클래스를 하나 만들었습니다.
만들고보니 해당 클래스와 `UserAgent` enum의 이름이 중복됩니다. 컴파일에는 문제가 없지만 이런 중복되는 이름은 피해야할까요??

2021-06-14 07:38 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    @NonNull
네 맞습니다. Required args constructor로 생성할 필드를 지정해주기 위해 사용하였습니다.

2021-06-14 08:20 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    }
말씀은 Comment에 equals hashCode를 오버라이딩해서 `Long commentId`말고 `Comment comment`를 받아서 비교를 하라는 말씀이시죠??
근데 그렇게하면 `matchComment()`를 호출하는 부분에서 Comment를 한번 찾아서 넣어줘야되더라구요. 그리고 Comment에 대한 Repository는 사용하지 않고 있어서 그렇게 하기도 좀 모호해 지는 부분이 있습니다.
그래서 일단 메소드 이름을 `matchCommentId()`로 이름을 변경했습니다.

2021-06-14 08:24 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    private List<Label> labels;
ManyToMany 맵핑 사용을 지양하는 이유가 join table에 새로운 컬럼이 추가되는 경우가 많기 때문이라고 들었는데, 저희 프로젝트 단에서는 새로운 컬럼이 추가될 필요가 없어 해당 맵핑을 사용해보았습니다ㅎㅎ 혹시 이 외에도 다른 문제점이 발생할 수 있을까요?

2021-06-14 11:22 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/IssueRepository.java
> +    @Transactional
Service 단으로 이동하였습니다!

2021-06-14 12:05 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
`@OneToMany(cascade = {PERSIST, MERGE}, orphanRemoval = true)`로 수정하였습니다.  사실 잘 모르고 저렇게 설정했었는데 이노와 함께 공부해보니 연관엔티티도 함께 영속화하려면 persist를 설정해주어야 하고, detached 상태에서 연관 엔티티의 변경 사항을 반영하려면 merge를 설정해주어야 한다고 해서 일단 저렇게 설정하였습니다.

그리고 comment만 삭제했을 때 issue가 살아있어도 comment가 db에서 삭제되도록 orphanRemoval을 true로 설정해주었습니다.

2021-06-14 12:21 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/web/dto/reqeust/IssueRequestDTO.java
> +                .comments(new ArrayList<>(Collections.singletonList(new Comment(comment, LocalDateTime.now(), author))))
Issue 내부에 create 메서드를 정의한 뒤 해당 메서드에서 Issue를 생성하는 방식으로 변경하였습니다.

2021-06-14 12:23 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
`IssueRequestDTO` 클래스에서 `toEntity()` 메소드를 사용하여 `Issue`를 만들어서 부족한 부분을 `create()` 메소드로 채워줬었는데 해당 부분 삭제 후 이름에 맞게 `create()` 메소드를 static으로 만들어 사용했습니다.

2021-06-14 12:40 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +        }
넵! 0번째 코멘트는 이슈 생성 시에 타이틀과 함께 생성되는 기본 코멘트라 삭제할 수 없도록 설정했습니다.

2021-06-14 12:40 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
`Issue`와 `Comment`가 `OneToMany`로 단방향 매핑이 되어있습니다. `Comment`에는 `Issue`를 가지고있지 않아요.
처음 구현했을 때 단방향 매핑을 할 줄 몰라서 `Comment` 쪽에도 `Issue`를 넣어주도록 양방향 매핑을해서 구현했었는데 현재 프로젝트에서는 굳이 사용할 필요성이 없어 단방향으로 구현했습니다.

지금 말씀을 해주신게 양방향 매핑을 염두에 두고 말씀을 해주신 것 같아서 질문 드립니다. 양방향 매핑을 하고 연관관계 편의 메소드를 만들어 사용해야 할까요??

2021-06-14 12:54 UTC, ksundong commented on BE/build.gradle
> +	id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
새로운 프로젝트를 진행하느니 만큼 최신 설정을 따르는게 좋다고 생각합니다.
더군다나 업데이트 되지 않는 기술은 채택하는데 굉장히 고민을 많이해야 한다고도 생각합니다.

또한 개발자는 신기술적용에 있어서 적극적인 태도를 보이는 편이 좋다는게 제 생각이기도 하지만, 강요하지는 않겠습니다!
어렵다면 다음 기회에 도전해보세요.

2021-06-14 12:54 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final GitHubUtil gitHubUtil;
네~ 저는 Util 클래스는 static 메서드를 제공하는 클래스로 정의하는 편입니다.
그게 대부분 일반적이고요.

2021-06-14 12:58 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private String userUri;
필드 주입은 권장되지 않는 패턴입니다.

생성자 주입은 다음과 같이 작성해줄 수 있습니다.

```java
public GitHubOAuth(@Value("${github.access.token.uri}") String accessTokenUri) {
    this.accessTokenUri = accessTokenUri;
}
```

왜 생성자 주입을 권장하는지는 직접 찾아보시면 면접 준비에도 도움이 되지 않을까 싶네요.
의존성을 주입하는 여러가지 방법중 가장 최선의 방법은 생성자 주입이고, 이 패턴을 따르시는 것을 추천합니다.

2021-06-14 13:00 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
항상 확장가능한 설계를 기저에 깔아두고 생각해보시면 쉽습니다.
현재의 의존성은 필요한 객체가 직접 생성하고 있습니다. 이는 우리가 말하는 의존성 주입과는 거리가 먼 방향입니다.

별도의 Bean으로 등록해두고, 주입을 받는다면 의존성 주입을 받아서 변경에 유연하게 설계해줄 수 있을겁니다.
또한, 테스트도 더 쉬워질테고요. 한 번 테스트 코드를 작성해보시면 어떤 얘긴지 더 잘 아실 수 있을겁니다.

2021-06-14 13:00 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +                .clientSecret(gitHubUtil.verifyClientSecret(userAgent))
verify가 하는 일과 get을 나누면 좋겠죠?
가져오는 것에 get을 사용하는 것엔 큰 이견이 없습니다~

2021-06-14 13:04 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +                .blockOptional()
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html
내용이 좀 바뀌었습니다. deprecated 될 예정이었으나, maintenance 될 예정으로 바뀌었습니다.
만약에 동기 + 블로킹이 필요하다면 그대로 RestTemplate을 사용하셔도 아무런 문제가 없습니다. 사용을 시도해보신점은 잘 하신 것 같아요~

2021-06-14 13:04 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/OAuth.java
> +    GitHubUserResponseDTO getUserInfo(String token);
리턴타입이 GitHub이라는 것이 드러나고 있습니다.
인터페이스는 추상적인 정보를 다루는 편이 변경에 유리합니다.

2021-06-14 13:09 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/GitHubUtil.java
> +public class GitHubUtil {
Utility 클래스는 일반적으로 공통적으로 자주 사용되는 기능이면서 비즈니스 로직과는 관계없는 기능들을 다루는 클래스입니다.
상태가 필요없고, static 메서드를 제공하고, 인스턴스 생성을 허용하지 않습니다.(이건 제가 사용하는 방식인데, 다른 분들과 차이가 있을 수 있습니다.)

반면 Service 클래스는 비즈니스 로직에 대한 특정 기능을 특화해서 제공하는 클래스입니다. 상태가 필요할 수도 있으며(보통 의존성으로 주입받습니다.) 비즈니스 로직에 대한 특정 처리를 담당합니다.

대략 이런 차이가 있다고 생각하시면 좋을 것 같아요.
그리고, 가급적이면 Utility 클래스는 정말 필요한 부분만 도입하고, 대부분은 Service를 이용하시면 좋을 것 같다는 생각이 듭니다.

2021-06-14 13:11 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +    IOS("IssueTrackerIOS");
사실 저는 헤더를 직접세팅할 필요가 있을까? 하는 생각이 들긴 해요.
이건 어차피 개발팀의 정책이니 제가 더이상 신경쓰는건 방해만 될 것 같네요.

POSTMAN에 대한 처리가 들어갈 필요가 있나? 하는 생각이 드네요. ㅎㅎ

2021-06-14 13:13 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +        String product = getUserAgent(userAgent);
사실 자주 사용되는 이름은 중복될 가능성이 높습니다. 이럴 때에 저는 이 둘이 같은 곳에서 사용될 가능성이 있는지를 생각해보는데요.
왜냐하면 하나는 풀패키지 경로를 작성해주어야 하기 때문입니다.

그러면 코드가 굉장히 읽기 힘들어지고 복잡해지게됩니다.
따라서 다른 네이밍을 사용해주는게 좋은 상황이지 않을까? 하는 생각이 드네요.

2021-06-14 13:13 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    @NonNull
음.. 그렇군요.

2021-06-14 13:16 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    }
사실 id라는 비즈니스 키를 가지고 비교하는건 별로 좋지 않습니다.
둘 다 null이라면 같을까요? 다를까요? 아마 NPE가 발생하겠죠?
id만 가지고 '같다.' 라고 판단하는 것은 위험한 선택일 수 있습니다.

JPA를 사용하시면서 많은 고민을 해보셨으면 좋겠네요.

2021-06-14 13:19 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    private List<Label> labels;
말씀하신 이유가 대표적인 이유고, 추가적으로 필요가 없다 라고 단정짓는건 별로 좋지 않은 습관이라고 생각합니다.
확장 가능성이 있는 설계를 알고도 사용하지 않는다면, 나중에 매우 뼈아플 수 있습니다.

물론 ManyToMany도 사용하라고 만들어 둔 기능이니만큼 사용하셔도 됩니다~

2021-06-14 13:20 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
네 학습 열심히 하셨네요! 👍

2021-06-14 13:21 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
앗 단방향 매핑이었군요. 제가 실수했네요.
의도된 설계라면 그냥 지나가셔도 좋습니다! 저는 당연히 양방향 매핑이 되어있을 거라고 생각했네요.

2021-06-14 13:21 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +        }
넵 이해했습니다!

2021-06-14 13:22 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +        }
예외를 발생시키는 것도 좋아보여요~

2021-06-14 13:34 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
해당 메서드들을 Service로 이동하였습니다. 

현재는 label을 get하지 않고 필터링만 해주고있기 때문에 N+1 쿼리 문제가 발생하지 않는 것 같은데 맞나요..? 혹시 N+1 쿼리 문제에 대한 위험성을 줄이려면 어떻게 작성하는게 좋을까요? 
LAZY로 전략이 설정되어 있으면 처음에 findAll()을 할 때 모든 entity가 로딩되지 않고 있다가, 뒤에 get을 할 때 로딩되기 때문에 N만큼의 추가적인 쿼리가 발생하고 해당 문제를 해결하기 위해서는 fetch join이나 entity graph 등을 사용하는 것으로 이해했는데 제대로 이해한 게 맞을까요? 이노랑 N+1 쿼리에 대해 공부해봤는데 아직 이해가 부족하여 제대로 이해한 건지 모르겠습니다.

2021-06-14 13:47 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/exception/ElementNotFoundException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
말씀해주신 의도가 400번대 코드는 맞지만 다른 상태코드를 말씀하시는건지 아니면 아싸리 400번대가 아니라 500을 염두에 두고 말씀하신건지 잘 모르겠네요.

일단 400번 에러를 보낸 이유가 엔티티를 db에서 찾을 때 클라이언트측에서 보내주는 정보를 토대로 검색을 하기 때문에 해당 데이터가 없다면 클라이언트측의 문제라 생각해서 400번을 달았습니다.

2021-06-14 13:55 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<Issue> closedIssues = issueRepository.findAllByIsOpenFalse();
페이징 처리를 염두해보고 작성한 코드인데 아직 적용을 하지 못했어요😢 추후 limit과 offset을 적용하여 페이징 처리를 할 예정입니다.

2021-06-14 13:59 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<IssueResponseDTO> issues = filterByStatus(status).stream()
전부 이슈에 관련된 메서드라 issueService 안에서 관리하고 있는데 어떻게 분리하면 좋을까요?
예를 들어, issueService 내부의 updateLabels 등의 메서드는 이슈의 레이블을 업데이트 하는 메서드인데 labelService에서 issueRepository를 받은 뒤 저장하는게 더 나은 구현일까요? 어떻게 리팩토링할지 감이 안와서 조언해주시면 감사하겠습니다!

2021-06-14 14:03 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        System.out.println(issue.toString());
프린트문 사용한건 잠깐 찍어보고 항상 삭제를 하는데 요건 못했네요ㅎㅎ;;
지웠습니다!!

2021-06-14 14:13 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        }
IN 쿼리를 사용하여 아래와 같이 변경하였습니다. 이렇게 하니까 좋네요🙂
```java
    @Query("update Issue i set i.isOpen = :isOpen where i.id in (:idList)")
    void updateStatusBy(boolean isOpen, List<Long> idList);
```

2021-06-14 14:15 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
그리고 지금 확인해봤는데, WebClient는 따로 미리 설정된 Bean은 없네요!

2021-06-14 14:18 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +    }
말씀이 잘 이해가 안되는데 조회를 하는 `IssueLookUpService`와 조작을 하는 `IssueOperationService` 클래스로 분리를 하란 말씀일까요??

2021-06-14 14:19 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
서비스에 있어야 할지는 더 생각해보시면 좋을 것 같고요.
labels를 stream을 생성하는 시점에서 LazyLoading이 동작할겁니다.

N+1을 줄이기 위해서는 적절한 fetch 전략이 필요합니다. 말씀하신 fetch join, entity graph, batch size 조정등의 방안이 있겠죠.
제일 중요한건 이것이 N + 1 문제를 발생시킬 여지가 있는지를 파악하는 시각이 중요하다고 생각합니다.
이를 이해하기 위해서는 JPA의 Lazy Loading에 대해서 좀 더 학습하시면 좋을 것 같다는 생각이 드네요.

어떤 사용되는 시점에 Loading이 되는지를 알면, 쉽게 이해하실 수 있지 않을까 싶어요.

2021-06-14 14:21 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +    }
이 부분은 추후에 필터링 조건이 추가되면 SearchRequest와 같은 DTO를 만들어 boolean이나 Enum 등으로 개선해보려고 했는데 아직 적용하지 못했네요😂 곧 필터링 조건을 추가하며 말씀주신 내용 개선해보겠습니다.

2021-06-14 14:22 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +    }
해당 메소드들 전부 이슈의 코멘트를 조작하거나, 이슈의 라벨, 마일스톤 등을 조작할 때 사용하는 메소드들이라 `IssueService`에 만들었습니다. 그래도 `service`를 분리를 하는게 좋을까요??
만약 분리를 하게 된다면 `service`의 이름도 이슈관련 로직들이라 고민이 되는데 어떤식으로 하면 좋을까요??

2021-06-14 14:23 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/exception/ElementNotFoundException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
사용자가 잘못된 데이터를 보냈는지 판단하는 예외는 아닌 것 같습니다.
사용자가 잘못 요청하였다면 4xx 에러를 반환하는 것은 맞습니다. 다만, 상태코드의 종류를 보고 적절한 상태코드를 선정해야겠죠.
404 Not Found 라는 유명한 상태코드는 어떤가요? 훨씬 의도한 바를 잘 전달해줄 수 있을 것 같습니다.

클라이언트 측 에러와 서버측 에러를 판단하는 기준은 간단합니다. 이것이 다시 제대로 요청되었을 때, 정상 응답이 가능한지를 판단하시면 됩니다.
400번대 응답은 사용자가 잘못 요청했으니, 다시 요청해보라는 것을 의미합니다. (일부 상태코드는 해당 요청은 아무리 다시 요청해도 정상 응답하지 않음을 안내하기도 합니다만, 일반적인 경우를 말씀드렸어요.)
500번대 응답은 서버가 현재 응답을 제대로 할 수 없음을 안내합니다. 제대로 요청했을 수도 있고, 아닐 수도 있지만 서버를 작성하는 입장에서는 별도의 처리가 불가능한 경우 500번대 응답을 줄 수 있다고 말씀드리고 싶네요.

2021-06-14 14:25 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<IssueResponseDTO> issues = filterByStatus(status).stream()
생각해보면, 이슈랑 관련되어있지 issue 자체에 대한 것은 아니지 않나요?
서비스의 계층 구조를 만들어서 처리를 분리하는 것도 방법이라고 생각됩니다.
아니면, 서비스를 정말 Thin하게 만들어서, 여러개의 메서드를 나열하더라도 가독성을 높이는 방안도 있습니다.

2021-06-14 14:25 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/service/MilestoneService.java
> +    private final LabelRepository labelRepository;
MilestonesResponseDTO에 labels의 수를 보내주기로 클라이언트 개발자들과 협의하여 불가피하게 labelRepository에서 count를 조회하게 되었습니다.

2021-06-14 14:26 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
> +        this.token = null;
해당 토큰은 우리 서버의 jwt가 아닌 GitHub에서 보내주는 access token입니다. 이름을 바꾸는게 좋을까요??ㅋㅋㅋ;;

2021-06-14 14:29 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/service/UserService.java
> +                () -> new ElementNotFoundException("Cannot find user by given user id.")
UserNotFoundException을 정의해주었습니다. 다른 엔티티에 대해서도 각각 커스텀 예외를 만들어 주는 게 좋을까요?

2021-06-14 14:30 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
> +    @LoginRequired
db에 데이터를 쓸 때 무조건 유저정보가 필요한 API들만 우선적으로 붙였습니다.
추후 유저 체크를 하는 API들에도 다 붙여서 검사할 예정입니다!!

2021-06-14 14:31 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
> +    public void changeStatus(@RequestBody IssueNumbersRequestDTO issueNumbersRequestDTO, @RequestParam String status) {
status값은 쿼리 파라미터로 보였으면 좋겠어서 issue number와 따로 받았는데 수정하는게 좋을까요?😮

2021-06-14 14:34 UTC, eNoLJ commented on BE/build.gradle
> +	id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
`또한 개발자는 신기술적용에 있어서 적극적인 태도를 보이는 편이 좋다는게 제 생각이기도 하지만` 이 부분 뜨끔하네요ㅋㅋㅋㅋㅋㅋㅋ 최대한 그러려고 노력해보겠습니다. 좋은 말씀 감사드립니다!!

2021-06-14 14:39 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
@ksundong 현재도 계속 반영 중인데 해당 부분 아직 푸시를 안했어요!! 곧 푸시하도록 하겠습니다.

2021-06-14 14:47 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/OAuth.java
> +    GitHubUserResponseDTO getUserInfo(String token);
아 그 부분이였군요!! 말씀해주시니까 보이네요. 만약 다른 OAuth 로그인을 구현하게 되면 어색해지겠네요.
감사합니다.

2021-06-14 14:49 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/GitHubUtil.java
> +public class GitHubUtil {
오! Util 클래스를 만드는 기준이 애매했었는데 디온 리뷰 덕에 많이 배워가네요. respository와 service를 1대1 대응하는 방식으로 만들고 있었는데 다음부터는 디온께서 말씀해주신 부분을 적용해보겠습니다👍👍

2021-06-14 14:54 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +    IOS("IssueTrackerIOS");
POSTMAN은 테스트의 용이함을 위해 추가해주었었는데, 최종 코드 및 배포하기 전에는 제거할게요!ㅎㅎ
헤더에 대해 주신 의견도 고민해보겠습니다!ㅎㅎ

2021-06-14 14:55 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/util/UserAgent.java
> +        String product = getUserAgent(userAgent);
오호... 단순히 생각했었는데 그런 번거로움이 있을 수 있겠네요. 다시 UserAgentDTO로 이름을 바꿨습니다!!

2021-06-14 14:57 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
롬복을 들어내는 것에 어려움이 있네요ㅠㅠ 현재 코드를 보면 Setter 정도만 들어낼 수 있을 것 같은데, 도메인에서는 setter를 직접 쓰는 것보다 updateFiledName과 같은 식으로 쓰는게 좋다는 말을 들어본 것 같습니다. 
아니면 Builder를 클래스에 정의한 것이 좋지 않은 구현 방식일까요?

저희도 롬복을 남용하다는 느낌이 드는데 어떻게 개선해야 좋을지 감이 안와 여쭤봅니다!!

2021-06-14 14:58 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    }
음... 근데 그렇게 보면 다른 키들도 null이 들어올 수 있어서 같은 문제가 발생되지 않나요??
그래서 해당 로직 전에 id가 null인지 체크를 해주는 로직을 추가하면 어떨까 생각되는데 어떨까요??

2021-06-14 14:59 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
아래와 같은 형식으로 등록해주었습니다!
```java
    @Bean
    public HttpClient httpClient() {
        return HttpClient.create().resolver(DefaultAddressResolverGroup.INSTANCE);
    }

    @Bean
    public WebClient webClient(HttpClient httpClient) {
        return WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
    }
```

2021-06-14 15:01 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +                .blockOptional()
저번 프로젝트 때 deprecated된다는 안내메시지를 봐서 적용해봤던거 같은데 maintenance로 바뀌었군요!ㅋㅋㅋ 
뭔가 RestTemplate에 비해 더 가독성이 좋다는 장점도 있는 것 같아요ㅎㅎ

2021-06-14 15:03 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    @NonNull
혹시 저렇게 사용하면 너무 롬복을 남용하는 걸까요? 잘 몰라서 여쭤봅니다😭

2021-06-14 15:09 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/issue/Issue.java
> +    }
답변 감사합니다! 해당 부분에 대해서는 이노와 더 공부해볼게요💪💪

2021-06-14 15:12 UTC, eNoLJ commented on BE/src/main/java/com/jane_eno/issue_tracker/exception/ElementNotFoundException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
조언해주신거에 따라 404로 변경했습니다. 항상 400, 404 헷갈리네요...
그리고 클라이언트측 에러와 서버측 에러 판별에 기준을 정리해주셔서 감사합니다!! 항상 고민되었던 부분인데 앞으로는 좀 더 정확하고 빠르게 판단할 수 있겠네요ㅎㅎ

2021-06-14 15:59 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/auth/GitHubOAuth.java
> +    private final WebClient webClient = WebClient.builder().clientConnector(new ReactorClientHttpConnector(httpClient)).build();
그리고 놓쳤던 부분인데 말씀주신대로 빈으로 등록해 놓으면 테스트 작성할 때도 사용할 수 있겠네요! 조언 감사합니다😊

2021-06-14 16:12 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<IssueResponseDTO> issues = filterByStatus(status).stream()
서비스의 계층구조를 만드는 방식 적용에 대해 고민하고 적용해볼게요!
서비스를 thin하게 만든다는 건 쿼리를 사용해서 대부분의 로직을 repository에서 처리하하도록 위임하는 걸로 이해하면 될까요? Querydsl 사용 예시를 보면 repository단에서 아예 dto로 변환된 객체를 반환하기도 하던데 이에대한 디온의 생각이 궁금해요☺

2021-06-15 13:46 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
가급적이면 Getter, Builder를 제외하고는 손으로 작성해보세요.
Builder도 생성자 위에 작성하는 편이 안전하다고 생각합니다.

2021-06-15 13:47 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    @NonNull
저같은 경우에는 Require를 표시하기 위해서는 final을 사용해야한다고 생각합니다.
Nonnull은 거기에 null 불가능까지 표현하기 위함이겠죠?
일단 컴파일 된 코드가 추측이 된다면 그대로 두시고, 아니라면 풀어두는 것을 추천합니다.

2021-06-15 13:48 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    }
해당 로직에서도 null 체크를 해주면 됩니다.
equals hashcode를 intellij를 이용해 만들어보세요~

2021-06-15 13:52 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<IssueResponseDTO> issues = filterByStatus(status).stream()
아뇨 아뇨 아뇨~ 쿼리를 이용해서 처리하는 것은 좋지 않은 패턴입니다.
그렇게 해야하는 경우가 있지만, 일반적인 객체지향 애플리케이션에서는 그렇게 해주시면 매우 유지보수 하기 힘들어질 수 있어요.
제가 말씀 드린 부분은 Model이라고 불리는 Domain영역에서 로직을 전개해나가는 것을 의미했습니다.

추가로 DTOProjection은 필요하면 사용하시되, 남용하지 마시라는 말씀을 드리고 싶네요~

2021-06-15 13:55 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +    }
네 CQRS라고 불리는 방식을 한 번 시도해보시는 것도 좋아보였어요.
https://www.popit.kr/cqrs-eventsourcing/
여기서 '일반'을 한 번 시도해보셔도 좋을 것 같습니다.

그리고 조회와 조작을 분리하면, 위에서 말씀하신 DTOProjection의 포인트를 더 잘 잡을 수도 있을거에요~

2021-06-15 13:56 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +    }
이슈의~ 에대한 서비스를 만들고 이에 대한 처리를 위임해주는 방식으로 설계해보는건 어떨까요?
아니면 이슈의~에 대한 도메인에 책임을 넘겨주는 방식도 있을 것 같아요.
한 번 고민해보면 좋을 것 같습니다!!

2021-06-15 13:56 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/MilestoneService.java
> +    private final LabelRepository labelRepository;
넵~

2021-06-15 13:57 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/user/User.java
> +        this.token = null;
앗 그렇군요 ㅋㅋㅋ 로그아웃한다고 token을 날릴 필요는 없습니다.

2021-06-15 13:57 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/service/UserService.java
> +                () -> new ElementNotFoundException("Cannot find user by given user id.")
넵 당연하죠!

2021-06-15 13:57 UTC, ksundong commented on BE/src/main/java/com/jane_eno/issue_tracker/web/IssueController.java
> +    public void changeStatus(@RequestBody IssueNumbersRequestDTO issueNumbersRequestDTO, @RequestParam String status) {
보통은 body로 받지만, elasticsearch도 그렇고 혼용해서 쓰셔도 아무런 문제가 없긴 합니다.
다만 사용하는 입장에서는 헷갈릴 여지가 분명히 있긴해요.

2021-06-15 13:59 UTC, ksundong approved these changes
피드백 해주시느라 고생하셨습니다!
다음 PR이 기대되네요~

2021-06-15 13:59 UTC, merged

2021-06-15 14:23 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/domain/comment/Comment.java
> +    @NonNull
NoArgsConstructor가 정의된 경우 `@NoArgsConstructor(force = true)`로 정의하지 않으면 final로 필드 선언 시 초기화되지 않은 필드가 존재할 수 있다는 에러가 발생하여 차선책으로 NonNull 애노테이션을 붙였습니다.

롬복을 적용하고나면 적용할 수 있는 부분은 다 적용하는게 좋다고 생각했었는데 디온의 코멘트들 덕분에 getter나 builder 정도에만 적용하고 builder도 생성자 위에 정의하는 방식으로 꼭 필요한 부분에만 사용할 수도 있다는 점을 배웠습니다. 이것저것 많이 여쭤봤는데 다 친절하게 답변해주셔서 감사합니다🙏

2021-06-15 14:29 UTC, janeljs commented on BE/src/main/java/com/jane_eno/issue_tracker/service/IssueService.java
> +        List<IssueResponseDTO> issues = filterByStatus(status).stream()
그렇군요!! 아래 코멘트를 보고 쿼리를 더 적극 활용해야겠다 싶었는데 쿼리를 사용하는 것이 나은 영역과 도메인 영역에서 로직을 전개하는 부분을 잘 판단해봐야겠네요! 이 브랜치에 아직 머지하지는 않았지만 오늘 querydsl을 활용하여 검색 조건에 따라 이슈를 필터링하는 부분을 구현했는데 다음 pr에서 코드리뷰를 받고 개선해봐야겠습니다ㅎㅎ 

+) 디온 말씀대로 issueService가 너무 커서 저희도 메서드 찾기가 어렵고 헷갈리는 부분이 많아 분리해야겠다고 생각했는데 주신 코멘트들 참고하여 다음 pr까지 개선해보겠습니다!
```
QueryDSL 의존성은 있는데 아직 사용은 하지 않으신 것 같네요. QueryDSL을 사용해서 보다 DB를 적극적으로 이용해보시기 바랍니다.
전반적으로 느껴지는 느낌은 너무 DB를 다루지 않는 느낌이 많이 들었습니다. 몇몇 부분은 객체에서 처리해주는 것이 아니라 DB에서 처리해주는 것이 더 나은 부분이 있었습니다.
```

2021-06-15 14:44 UTC, janeljs commented
@ksundong 이것저것 여쭈어봤는데 질문들 친절하게 답변주셔서 감사합니다🥰

 + 이노가 디온의 엄청난 팬이라 매우 즐거워하며 코드를 고치더라구요!ㅋㅋ 저는 요즘 PR도 자주 못보내고 프로젝트 끝나면 지쳐서 코드리뷰 반영에 소홀했었는데 열심히 고치니 배우는게 많네요ㅎㅎ 다음 리뷰도 잘 부탁드립니다😆